# Generated by Django 5.2.7 on 2025-10-09 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('sender', models.TextField()),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('attachments_meta', models.JSONField(blank=True, default=list)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
