# Generated by Django 5.2.7 on 2025-10-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='verdict',
            field=models.CharField(db_index=True, default='unknown', max_length=32),
        ),
    ]
