# Generated by Django 5.2.7 on 2025-10-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailrecord_reasons_emailrecord_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='message_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
