# Generated by Django 5.2.7 on 2025-10-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emailrecord_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecord',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='emailrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='attachments_text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='body_with_ocr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='ocr_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='attachments_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='sender',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='verdict',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
