# Generated by Django 5.0.6 on 2025-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_emailrecord_analysis_remove_emailrecord_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainWhois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='no-data', max_length=50)),
                ('whois_score', models.FloatField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
