

# api/url_blocklist.py
from pathlib import Path
import re
from urllib.parse import urlparse

import tldextract


# ---------------------------------------------------------------------------
# Paths to preprocessed domain lists
# Generated by preprocess_url_blocklist.py:
#   - benign_hosts.txt
#   - malicious_hosts.txt
# Each file contains ONE root domain per line (e.g. "google.com").
# ---------------------------------------------------------------------------

DATA_DIR = Path(__file__).resolve().parent / "data"
BENIGN_TXT_PATH = DATA_DIR / "benign_hosts.txt"
MALICIOUS_TXT_PATH = DATA_DIR / "malicious_hosts.txt"

# In-memory sets of root domains
BENIGN_ROOTS: set[str] = set()
MALICIOUS_ROOTS: set[str] = set()

# Regex to find URLs in body text
_URL_REGEX = re.compile(
    r"""(?P<url>
        https?://[^\s<>"']+|
        www\.[^\s<>"']+
    )""",
    re.IGNORECASE | re.VERBOSE,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _root_domain_from_host_or_url(s: str) -> str | None:
    """
    Convert a hostname or URL into a root domain using tldextract.

    Examples:
      "https://console.cloud.google.com" -> "google.com"
      "www.google.com"                  -> "google.com"
      "vilastiles.com/path"            -> "vilastiles.com"
    """
    if not s:
        return None
    s = str(s).strip()
    if not s:
        return None

    ext = tldextract.extract(s)
    # ext = (subdomain, domain, suffix)
    if not ext.domain or not ext.suffix:
        return None

    root = f"{ext.domain}.{ext.suffix}".lower()
    return root or None


def _host_from_email(sender: str) -> str | None:
    """
    Extract domain from email address, e.g. 'x@youtube.com' -> 'youtube.com'.
    """
    if not sender:
        return None
    m = re.search(r"@([A-Za-z0-9\.-]+)", sender)
    if not m:
        return None
    host = m.group(1).lower()
    return host or None


def _load_blocklists_from_txt():
    """
    Load preprocessed root domains from benign_hosts.txt and malicious_hosts.txt
    into BENIGN_ROOTS and MALICIOUS_ROOTS sets.
    """
    global BENIGN_ROOTS, MALICIOUS_ROOTS

    benign = set()
    malicious = set()

    if BENIGN_TXT_PATH.exists():
        try:
            for line in BENIGN_TXT_PATH.read_text(encoding="utf-8", errors="ignore").splitlines():
                d = line.strip().lower()
                if d:
                    benign.add(d)
        except Exception as e:
            print(f"[url_blocklist] ❌ Error reading {BENIGN_TXT_PATH}: {e}")
    else:
        print(f"[url_blocklist] ⚠️ Benign list not found at {BENIGN_TXT_PATH}")

    if MALICIOUS_TXT_PATH.exists():
        try:
            for line in MALICIOUS_TXT_PATH.read_text(encoding="utf-8", errors="ignore").splitlines():
                d = line.strip().lower()
                if d:
                    malicious.add(d)
        except Exception as e:
            print(f"[url_blocklist] ❌ Error reading {MALICIOUS_TXT_PATH}: {e}")
    else:
        print(f"[url_blocklist] ⚠️ Malicious list not found at {MALICIOUS_TXT_PATH}")

    BENIGN_ROOTS = benign
    MALICIOUS_ROOTS = malicious

    print(
        f"[url_blocklist] ✅ Loaded {len(MALICIOUS_ROOTS)} malicious and "
        f"{len(BENIGN_ROOTS)} benign root domains into memory (from .txt)."
    )


# Load on import
_load_blocklists_from_txt()


# ---------------------------------------------------------------------------
# Public API used by views.py
# ---------------------------------------------------------------------------

def extract_hosts(sender: str, body: str) -> set[str]:
    """
    Extract all root domains from sender + body text.

    Returns a set of strings like: {"google.com", "vilastiles.com"}.
    """
    roots: set[str] = set()

    # Sender email domain
    sender_host = _host_from_email(sender or "")
    if sender_host:
        rd = _root_domain_from_host_or_url(sender_host)
        if rd:
            roots.add(rd)

    text = body or ""
    for m in _URL_REGEX.finditer(text):
        url = m.group("url")
        rd = _root_domain_from_host_or_url(url)
        if rd:
            roots.add(rd)

    return roots


def assess_urls(sender: str, body: str) -> dict:
    """
    High-level helper for views.py.

    Returns:
      {
        "status": "malicious" | "benign" | "unknown",
        "hosts": [... all root domains extracted ...],
        "malicious_hosts": [...],
        "benign_hosts": [...]
      }
    """
    roots = extract_hosts(sender, body)
    malicious_hits = [h for h in roots if h in MALICIOUS_ROOTS]
    benign_hits = [h for h in roots if h in BENIGN_ROOTS]

    if malicious_hits:
        status = "malicious"
    elif benign_hits:
        status = "benign"
    else:
        status = "unknown"

    return {
        "status": status,
        "hosts": sorted(roots),
        "malicious_hosts": sorted(malicious_hits),
        "benign_hosts": sorted(benign_hits),
    }
